{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ritual-ledger.fullname" . }}-test-runner
  labels:
    {{- include "ritual-ledger.labels" . | nindent 4 }}
    app.kubernetes.io/component: test-runner
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
