apiVersion: v1
kind: Service
metadata:
  name: {{ include "ritual-ledger.fullname" . }}
  labels:
    {{- include "ritual-ledger.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ritual-ledger.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
